exports.FORM_FIELD_DEFAULTS = {
  STREQUIRED: 'N',
  DSFIELDEXAMPLE: '',
  DSACTIONSCRIPT: '',
  CODGROUPVALUE: '',
  STVIEWREPORT: 1,
  STSENDPARAMETERS: 'N',
  VLSIZE: 200,
  VLMAXLENGTH: 3000,
  VLMINLENGTH: '',
  VLCOLS: '',
  CODPARENTFIELD: '',
  CODPARENTFORM: '',
  CODFIELDTABLE: '',
  CODVALIDATION: '',
  DSFIELDURL: '',
  DSFORMULA: ''
}

exports.FIELD_TYPE_DEFAULTS = {
  CODFIELDTYPE: 1,
  CODFIELDFORMAT: 1,
  DSFIELDTYPENAME: 'Texto',
  DSFIELDTYPEMASK: '',
  STFIELDTYPETEXT: ''
}

exports.FIELD_FORMAT_DEFAULTS = {
  CODFIELDFORMAT: 1,
  DSFIELDFORMAT: 'TEXTO',
  DSFIELDFORMATALIAS: 'TEXT',
  DSALIAS: ''
}
